== GrowERp OFBiz plugin for the Flutter frontend.
////
check https://powerman.name/doc/asciidoc for format
////
=== Introduction
A plugin to serve the GrowERP frontend at https://github.com/growerp/growerp

== Installation
install Apache Ofbiz on Ubuntu: (works on any OS very similarly)
[source, bash]
----
git clone https://github.com/apache/ofbiz-framework.git ofbiz
git clone https://github.com/apache/ofbiz-plugins.git
cp ofbiz-plugins/ofbiz-rest-impl ofbiz/plugins
git clone https://github.com/growerp/growerp-ofbiz.git ofbiz/plugins/growerp
cd ofbiz
./gradlew loadAll
./gradlew ofbiz
----

== Extra for local development
When in development, we need to change ofbiz to make the rest interface using http instead of https which is the OFBiz default.

=== change OFBiz so you do not need a valid ssl certificate:
file: + 
plugins/ofbiz-rest-impl/webapp/ofbiz-rest-jersey/WEB-INF/controller.xml +
change: +
    from:     <request-map uri="main"><security https="true"/> +
    To:       <request-map uri="main"><security https="false"/>


Further you need apache2 in front of ofbiz.
install: 
[source, bash]
----
sudo apt install apache2
sudo a2enmod headers
sudo a2enmod mod_proxy
sudo a2enmod mod_proxy_ajp
----
replace file: /etc/apache2/sites-enabled/000-default.conf with this:
[source, config]
----
<Proxy *>
        AddDefaultCharset off
        Order deny,allow
        Allow from all
</Proxy>
ProxyVia On
<LocationMatch "/rest/">
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Headers "Authorization"
    Header always set Access-Control-Allow-Credentials "true"
</LocationMatch>
NameVirtualHost *:80
<VirtualHost *>
    ServerName localhost
    ServerAdmin you@example.com
    ProxyRequests Off
    ProxyPreserveHost On
    proxyPass /rest ajp://localhost:8009/rest
    proxyPassreverse /rest ajp://localhost:8009/rest
</VirtualHost>
----
when installed, restart apache2: +
systemctl restart apache2

then the rest interface should work with http://localhost/rest

If you know a beter way to avoid the XMLHttpRequest error?
Let me know!

